#!/bin/sh

DOT_BASENAME="dot"
DOT="${DOT:-$HOME/$DOT_BASENAME}"
ETC="$DOT/etc"
BACKUP_DIR="$HOME/dot_backup"
TIME=$(date +%Y%m%d_%H%M%S)

echodry() {
    echo '   ' "$@"
}

if [ "$DRY" != "" ]; then
    DRY=1
    echo "Dry run ================================================"
    EVAL="echodry"
else
    EVAL=eval
fi

cd "$DOT"
git submodule init
git submodule update
cd -

# ホームに必要なディレクトリを作っておく
$EVAL mkdir -p ~/bin ~/tmp ~/.vimundo

link() {
    # すでに同名のファイルが存在し、シンボリックリンクでないなら
    if [ -e "$HOME/$1" -a \! -L "$HOME/$1" ]; then
        # mvでバックアップしておく
        $EVAL mkdir -p $BACKUP_DIR
        echo "Backup: $1"
        $EVAL mv -v "$HOME/$1" "$BACKUP_DIR/$1.$TIME"
    fi
    if [ -L ~/$1 ]; then
        $EVAL rm ~/$1
    fi
    # シンボリックリンク作成
    $EVAL ln -snfv ${2:-$ETC/$1} ~/$1
}

cd "$ETC"

link .alias
link .bashrc
link .bash_profile
link .ctags
link .eslintrc.json
link .gdbinit
link .ghci
link .gitignore
link .gitconfig
link .inputrc
link .irbrc
link .irb_pry_common
link .my.cnf
link .profile
link .screenrc
link .sqliterc
link .pryrc
link .vim
link .zprofile
link .zshenv
link .zshrc
link .vimrc "$ETC/.vim/.vimrc"

$EVAL ln -snfv "$DOT/bin/atool" "$DOT/bin/acat"
$EVAL ln -snfv "$DOT/bin/atool" "$DOT/bin/adiff"
$EVAL ln -snfv "$DOT/bin/atool" "$DOT/bin/als"
$EVAL ln -snfv "$DOT/bin/atool" "$DOT/bin/apack"
$EVAL ln -snfv "$DOT/bin/atool" "$DOT/bin/arepack"
$EVAL ln -snfv "$DOT/bin/atool" "$DOT/bin/aunpack"

if [ "$DRY" != "" ]; then
    echo "Dry run ================================================"
fi
