#!/bin/sh

DOT_BASENAME="dot"
DOT="${DOT:-$HOME/$DOT_BASENAME}"
ETC="$DOT/etc"

. "$DOT/bin/_dryrun.sh"

$EVAL mkdir -p ~/bin ~/tmp ~/.vimundo

BACKUP_DIR="$HOME/dot_backup"
TIME=$(date +%Y%m%d_%H%M%S)

link() {
    if [ -e "$HOME/$1" -a \! -L "$HOME/$1" ]; then
        $EVAL mkdir -p $BACKUP_DIR
        echo "Backup: $1"
        $EVAL mv -v "$HOME/$1" "$BACKUP_DIR/$1.$TIME"
    fi
    $EVAL ln -sfv $ETC/$1 ~
}

cd "$ETC"

link .alias
link .bashrc
link .ctags
link .gdbinit
link .gdbinit.d
link .ghci
link .gitignore
link .gitconfig
link .inputrc
link .irbrc
link .my.cnf
link .profile
link .screenrc
link .sqliterc
link .pryrc
link .vim
link .zprofile
link .zshrc
$EVAL ln -sfv $ETC/.vim/.vimrc ~/.vimrc

if [ "$DRY" != "" ]; then
    echo "Dry run ================================================"
fi
