#!/bin/sh

DOT_BASENAME="dot"
DOT="${DOT:-$HOME/$DOT_BASENAME}"
ETC="$DOT/etc"
BACKUP_DIR="$HOME/dot_backup"
TIME=$(date +%Y%m%d_%H%M%S)

. "$DOT/bin/_dryrun.sh"

# ホームに必要なディレクトリを作っておく
$EVAL mkdir -p ~/bin ~/tmp ~/.vimundo

link() {
    # すでに同名のファイルが存在し、シンボリックリンクでないなら
    if [ -e "$HOME/$1" -a \! -L "$HOME/$1" ]; then
        # mvでバックアップしておく
        $EVAL mkdir -p $BACKUP_DIR
        echo "Backup: $1"
        $EVAL mv -v "$HOME/$1" "$BACKUP_DIR/$1.$TIME"
    fi
    if [ -L ~/$1 ]; then
        rm ~/$1
    fi
    # シンボリックリンク作成
    $EVAL ln -sfv ${2:-$ETC/$1} ~/$1
}

cd "$ETC"

link .alias
link .bashrc
link .ctags
link .gdbinit
link .gdbinit.d
link .ghci
link .gitignore
link .gitconfig
link .inputrc
link .irbrc
link .irb_pry_common
link .my.cnf
link .profile
link .screenrc
link .sqliterc
link .pryrc
link .vim
link .zprofile
link .zshrc
link .vimrc "$ETC/.vim/.vimrc"

if [ "$DRY" != "" ]; then
    echo "Dry run ================================================"
fi
