if g:color_list_loaded 
  finish
endif

for color_index in range(1, 255)
  exe "syntax match termColor" . color_index . ' /COLOR' . color_index . ' .*$/ containedin=vimLineComment'
  exe "hi termColor" . color_index .  " cterm=bold ctermfg=" . color_index . " ctermbg=None"
endfor


"COLOR10  lkasjdlaksdjasldj
"COLOR11  lkasjdlaksdjasldj
"COLOR12  lkasjdlaksdjasldj
"COLOR13  lkasjdlaksdjasldj
"COLOR14  lkasjdlaksdjasldj
"COLOR15  lkasjdlaksdjasldj
"COLOR16  lkasjdlaksdjasldj
"COLOR17  lkasjdlaksdjasldj
"COLOR18  lkasjdlaksdjasldj
"COLOR19  lkasjdlaksdjasldj
"COLOR20  lkasjdlaksdjasldj
"COLOR21  lkasjdlaksdjasldj
"COLOR22  lkasjdlaksdjasldj
"COLOR23  lkasjdlaksdjasldj
"COLOR24  lkasjdlaksdjasldj
"COLOR25  lkasjdlaksdjasldj
"COLOR26  lkasjdlaksdjasldj
"COLOR27  lkasjdlaksdjasldj
"COLOR28  lkasjdlaksdjasldj
"COLOR29  lkasjdlaksdjasldj
"COLOR30  lkasjdlaksdjasldj
"COLOR31  lkasjdlaksdjasldj
"COLOR32  lkasjdlaksdjasldj
"COLOR33  lkasjdlaksdjasldj
"COLOR34  lkasjdlaksdjasldj
"COLOR35  lkasjdlaksdjasldj
"COLOR36  lkasjdlaksdjasldj
"COLOR37  lkasjdlaksdjasldj
"COLOR38  lkasjdlaksdjasldj
"COLOR39  lkasjdlaksdjasldj
"COLOR40  lkasjdlaksdjasldj
"COLOR41  lkasjdlaksdjasldj
"COLOR42  lkasjdlaksdjasldj
"COLOR43  lkasjdlaksdjasldj
"COLOR44  lkasjdlaksdjasldj
"COLOR45  lkasjdlaksdjasldj
"COLOR46  lkasjdlaksdjasldj
"COLOR47  lkasjdlaksdjasldj
"COLOR48  lkasjdlaksdjasldj
"COLOR49  lkasjdlaksdjasldj
"COLOR50  lkasjdlaksdjasldj
"COLOR51  lkasjdlaksdjasldj
"COLOR52  lkasjdlaksdjasldj
"COLOR53  lkasjdlaksdjasldj
"COLOR54  lkasjdlaksdjasldj
"COLOR55  lkasjdlaksdjasldj
"COLOR56  lkasjdlaksdjasldj
"COLOR57  lkasjdlaksdjasldj
"COLOR58  lkasjdlaksdjasldj
"COLOR59  lkasjdlaksdjasldj
"COLOR60  lkasjdlaksdjasldj
"COLOR61  lkasjdlaksdjasldj
"COLOR62  lkasjdlaksdjasldj
"COLOR63  lkasjdlaksdjasldj
"COLOR64  lkasjdlaksdjasldj
"COLOR65  lkasjdlaksdjasldj
"COLOR66  lkasjdlaksdjasldj
"COLOR67  lkasjdlaksdjasldj
"COLOR68  lkasjdlaksdjasldj
"COLOR69  lkasjdlaksdjasldj
"COLOR70  lkasjdlaksdjasldj
"COLOR71  lkasjdlaksdjasldj
"COLOR72  lkasjdlaksdjasldj
"COLOR73  lkasjdlaksdjasldj
"COLOR74  lkasjdlaksdjasldj
"COLOR75  lkasjdlaksdjasldj
"COLOR76  lkasjdlaksdjasldj
"COLOR77  lkasjdlaksdjasldj
"COLOR78  lkasjdlaksdjasldj
"COLOR79  lkasjdlaksdjasldj
"COLOR80  lkasjdlaksdjasldj
"COLOR81  lkasjdlaksdjasldj
"COLOR82  lkasjdlaksdjasldj
"COLOR83  lkasjdlaksdjasldj
"COLOR84  lkasjdlaksdjasldj
"COLOR85  lkasjdlaksdjasldj
"COLOR86  lkasjdlaksdjasldj
"COLOR87  lkasjdlaksdjasldj
"COLOR88  lkasjdlaksdjasldj
"COLOR89  lkasjdlaksdjasldj
"COLOR90  lkasjdlaksdjasldj
"COLOR91  lkasjdlaksdjasldj
"COLOR92  lkasjdlaksdjasldj
"COLOR93  lkasjdlaksdjasldj
"COLOR94  lkasjdlaksdjasldj
"COLOR95  lkasjdlaksdjasldj
"COLOR96  lkasjdlaksdjasldj
"COLOR97  lkasjdlaksdjasldj
"COLOR98  lkasjdlaksdjasldj
"COLOR99  lkasjdlaksdjasldj
"COLOR100  lkasjdlaksdjasldj
"COLOR101  lkasjdlaksdjasldj
"COLOR102  lkasjdlaksdjasldj
"COLOR103  lkasjdlaksdjasldj
"COLOR104  lkasjdlaksdjasldj
"COLOR105  lkasjdlaksdjasldj
"COLOR106  lkasjdlaksdjasldj
"COLOR107  lkasjdlaksdjasldj
"COLOR108  lkasjdlaksdjasldj
"COLOR109  lkasjdlaksdjasldj
"COLOR110  lkasjdlaksdjasldj
"COLOR111  lkasjdlaksdjasldj
"COLOR112  lkasjdlaksdjasldj
"COLOR113  lkasjdlaksdjasldj
"COLOR114  lkasjdlaksdjasldj
"COLOR115  lkasjdlaksdjasldj
"COLOR116  lkasjdlaksdjasldj
"COLOR117  lkasjdlaksdjasldj
"COLOR118  lkasjdlaksdjasldj
"COLOR119  lkasjdlaksdjasldj
"COLOR120  lkasjdlaksdjasldj
"COLOR121  lkasjdlaksdjasldj
"COLOR122  lkasjdlaksdjasldj
"COLOR123  lkasjdlaksdjasldj
"COLOR124  lkasjdlaksdjasldj
"COLOR125  lkasjdlaksdjasldj
"COLOR126  lkasjdlaksdjasldj
"COLOR127  lkasjdlaksdjasldj
"COLOR128  lkasjdlaksdjasldj
"COLOR129  lkasjdlaksdjasldj
"COLOR130  lkasjdlaksdjasldj
"COLOR131  lkasjdlaksdjasldj
"COLOR132  lkasjdlaksdjasldj
"COLOR133  lkasjdlaksdjasldj
"COLOR134  lkasjdlaksdjasldj
"COLOR135  lkasjdlaksdjasldj
"COLOR136  lkasjdlaksdjasldj
"COLOR137  lkasjdlaksdjasldj
"COLOR138  lkasjdlaksdjasldj
"COLOR139  lkasjdlaksdjasldj
"COLOR140  lkasjdlaksdjasldj
"COLOR141  lkasjdlaksdjasldj
"COLOR142  lkasjdlaksdjasldj
"COLOR143  lkasjdlaksdjasldj
"COLOR144  lkasjdlaksdjasldj
"COLOR145  lkasjdlaksdjasldj
"COLOR146  lkasjdlaksdjasldj
"COLOR147  lkasjdlaksdjasldj
"COLOR148  lkasjdlaksdjasldj
"COLOR149  lkasjdlaksdjasldj
"COLOR150  lkasjdlaksdjasldj
"COLOR151  lkasjdlaksdjasldj
"COLOR152  lkasjdlaksdjasldj
"COLOR153  lkasjdlaksdjasldj
"COLOR154  lkasjdlaksdjasldj
"COLOR155  lkasjdlaksdjasldj
"COLOR156  lkasjdlaksdjasldj
"COLOR157  lkasjdlaksdjasldj
"COLOR158  lkasjdlaksdjasldj
"COLOR159  lkasjdlaksdjasldj
"COLOR160  lkasjdlaksdjasldj
"COLOR161  lkasjdlaksdjasldj
"COLOR162  lkasjdlaksdjasldj
"COLOR163  lkasjdlaksdjasldj
"COLOR164  lkasjdlaksdjasldj
"COLOR165  lkasjdlaksdjasldj
"COLOR166  lkasjdlaksdjasldj
"COLOR167  lkasjdlaksdjasldj
"COLOR168  lkasjdlaksdjasldj
"COLOR169  lkasjdlaksdjasldj
"COLOR170  lkasjdlaksdjasldj
"COLOR171  lkasjdlaksdjasldj
"COLOR172  lkasjdlaksdjasldj
"COLOR173  lkasjdlaksdjasldj
"COLOR174  lkasjdlaksdjasldj
"COLOR175  lkasjdlaksdjasldj
"COLOR176  lkasjdlaksdjasldj
"COLOR177  lkasjdlaksdjasldj
"COLOR178  lkasjdlaksdjasldj
"COLOR179  lkasjdlaksdjasldj
"COLOR180  lkasjdlaksdjasldj
"COLOR181  lkasjdlaksdjasldj
"COLOR182  lkasjdlaksdjasldj
"COLOR183  lkasjdlaksdjasldj
"COLOR184  lkasjdlaksdjasldj
"COLOR185  lkasjdlaksdjasldj
"COLOR186  lkasjdlaksdjasldj
"COLOR187  lkasjdlaksdjasldj
"COLOR188  lkasjdlaksdjasldj
"COLOR189  lkasjdlaksdjasldj
"COLOR190  lkasjdlaksdjasldj
"COLOR191  lkasjdlaksdjasldj
"COLOR192  lkasjdlaksdjasldj
"COLOR193  lkasjdlaksdjasldj
"COLOR194  lkasjdlaksdjasldj
"COLOR195  lkasjdlaksdjasldj
"COLOR196  lkasjdlaksdjasldj
"COLOR197  lkasjdlaksdjasldj
"COLOR198  lkasjdlaksdjasldj
"COLOR199  lkasjdlaksdjasldj
"COLOR200  lkasjdlaksdjasldj
"COLOR201  lkasjdlaksdjasldj
"COLOR202  lkasjdlaksdjasldj
"COLOR203  lkasjdlaksdjasldj
"COLOR204  lkasjdlaksdjasldj
"COLOR205  lkasjdlaksdjasldj
"COLOR206  lkasjdlaksdjasldj
"COLOR207  lkasjdlaksdjasldj
"COLOR208  lkasjdlaksdjasldj
"COLOR209  lkasjdlaksdjasldj
"COLOR210  lkasjdlaksdjasldj
"COLOR211  lkasjdlaksdjasldj
"COLOR212  lkasjdlaksdjasldj
"COLOR213  lkasjdlaksdjasldj
"COLOR214  lkasjdlaksdjasldj
"COLOR215  lkasjdlaksdjasldj
"COLOR216  lkasjdlaksdjasldj
"COLOR217  lkasjdlaksdjasldj
"COLOR218  lkasjdlaksdjasldj
"COLOR219  lkasjdlaksdjasldj
"COLOR220  lkasjdlaksdjasldj
"COLOR221  lkasjdlaksdjasldj
"COLOR222  lkasjdlaksdjasldj
"COLOR223  lkasjdlaksdjasldj
"COLOR224  lkasjdlaksdjasldj
"COLOR225  lkasjdlaksdjasldj
"COLOR226  lkasjdlaksdjasldj
"COLOR227  lkasjdlaksdjasldj
"COLOR228  lkasjdlaksdjasldj
"COLOR229  lkasjdlaksdjasldj
"COLOR230  lkasjdlaksdjasldj
"COLOR231  lkasjdlaksdjasldj
"COLOR232  lkasjdlaksdjasldj
"COLOR233  lkasjdlaksdjasldj
"COLOR234  lkasjdlaksdjasldj
"COLOR235  lkasjdlaksdjasldj
"COLOR236  lkasjdlaksdjasldj
"COLOR237  lkasjdlaksdjasldj
"COLOR238  lkasjdlaksdjasldj
"COLOR239  lkasjdlaksdjasldj
"COLOR240  lkasjdlaksdjasldj
"COLOR241  lkasjdlaksdjasldj
"COLOR242  lkasjdlaksdjasldj
"COLOR243  lkasjdlaksdjasldj
"COLOR244  lkasjdlaksdjasldj
"COLOR245  lkasjdlaksdjasldj
"COLOR246  lkasjdlaksdjasldj
"COLOR247  lkasjdlaksdjasldj
"COLOR248  lkasjdlaksdjasldj
"COLOR249  lkasjdlaksdjasldj
"COLOR250  lkasjdlaksdjasldj
"COLOR251  lkasjdlaksdjasldj
"COLOR252  lkasjdlaksdjasldj
"COLOR253  lkasjdlaksdjasldj
"COLOR254  lkasjdlaksdjasldj
"COLOR255  lkasjdlaksdjasldj
"COLOR256  lkasjdlaksdjasldj
"COLOR123  lkasjdlaksdjasldj

let g:color_list_loaded = 1
