#!/bin/sh

GREP_RESULT=`git diff --cached | grep -i KEY | grep AKI[A]` 
if [ -n "${GREP_RESULT}" ]; then
    echo 'AWS_ACCESS_KEYがインデックスに入っている可能性があります。git diff --cachedで確認してください。'
    echo "${GREP_RESULT}" 
    exit 1 
else
    exit 0
fi
